export const metadata = {
  title: 'Learning Next',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><h1>Header</h1>{children}<h1>footer </h1></body>
    </html>
  )
}
