export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function DocumentationLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
            {children}
            <h1>This is docs layout</h1>
        </>
    )
  }
  